AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: chapter07-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expired_at
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: chapter07-function
      CodeUri: ./src
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        Streams:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt Table.StreamArn
            BatchSize: 1
            StartingPosition: LATEST
